import Head from 'next/head'
//Components
import { MethodLink } from '@/components/MethodLink'
//Data
import { methods } from '@/data/methods'
import { Layout } from '@/components/Layout'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-4xl font-bold text-gray-900">Methods</h1>
        <ul className="mt-6 space-y-6">
          {methods.map((method) => (
            <li key={method.name}>
              <MethodLink {...method} />
            </li>
          ))}
        </ul>
      </Layout>
    </>
  )
}
